_name_or_path:
    value: Qwen/Qwen3.5-4B
_wandb:
    value:
        cli_version: 0.25.0
        e:
            xe0ohwxfed8wtyrhwt8sx1tizovywu7l:
                args:
                    - --model_name_or_path
                    - Qwen/Qwen3.5-4B
                    - --tune_mm_llm
                    - "True"
                    - --tune_mm_vision
                    - "False"
                    - --tune_mm_mlp
                    - "False"
                    - --dataset_use
                    - spar_234k%60,llava_hound_64k%60,vlm3r_scannet%60,vsi_appr_order%50
                    - --output_dir
                    - /project/peilab/jys/qwen3_5_output/only-replace-vggt-with-omega
                    - --cache_dir
                    - /project/peilab/jys/spatialstack_store/hf_cache/hub
                    - --bf16
                    - --per_device_train_batch_size
                    - "1"
                    - --gradient_accumulation_steps
                    - "8"
                    - --learning_rate
                    - "1e-5"
                    - --mm_projector_lr
                    - "1e-5"
                    - --vision_tower_lr
                    - "1e-6"
                    - --optim
                    - adamw_torch
                    - --model_max_length
                    - "12800"
                    - --data_flatten
                    - "False"
                    - --max_pixels
                    - "451584"
                    - --min_pixels
                    - "12544"
                    - --base_interval
                    - "2"
                    - --video_max_frames
                    - "8"
                    - --video_min_frames
                    - "4"
                    - --video_max_frame_pixels
                    - "1304576"
                    - --video_min_frame_pixels
                    - "200704"
                    - --num_train_epochs
                    - "1"
                    - --lr_scheduler_type
                    - cosine
                    - --weight_decay
                    - "0.01"
                    - --logging_steps
                    - "10"
                    - --save_strategy
                    - "no"
                    - --save_steps
                    - "0"
                    - --save_total_limit
                    - "0"
                    - --deepspeed
                    - scripts/zero2_opt.json
                    - --gradient_checkpointing
                    - --dataloader_num_workers
                    - "4"
                    - --group_by_modality_length
                    - "true"
                    - --seed
                    - "0"
                    - --report_to
                    - wandb
                    - --use_geometry_encoder
                    - "True"
                    - --run_name
                    - only-replace-vggt-with-omega
                    - --geometry_encoder_type
                    - vggt_omega_direct
                    - --geometry_encoder_path
                    - facebook/VGGT-Omega
                    - --feature_fusion_method
                    - deepstack_language_add
                    - --geometry_fusion_layers
                    - "0"
                    - "1"
                    - "2"
                    - --geometry_encoder_layers
                    - "11"
                    - "17"
                    - "23"
                codePath: SpatialStack/src/qwen_vl/train/train_qwen.py
                codePathLocal: src/qwen_vl/train/train_qwen.py
                cpu_count: 112
                cpu_count_logical: 224
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1888556142592"
                        used: "22423744512"
                email: yjiaag@connect.ust.hk
                executable: /home/dduab/.conda/envs/spatialstack/bin/python3.12
                git:
                    commit: cb832634f71f3c00ddc45ba4451b5a311bbae1a7
                    remote: git@github.com:Lfpast/SpatialStack-omega.git
                gpu: NVIDIA H800
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H800
                      uuid: GPU-1ab20658-e3a1-1ab8-ef9f-aa4ec51db5ba
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H800
                      uuid: GPU-36d5155d-0bef-60de-2a99-a8db65a17386
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H800
                      uuid: GPU-00a7faac-03e7-4a41-bc52-67638dd23463
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H800
                      uuid: GPU-ca432212-0e67-d65d-b5fc-1e33153e79f5
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H800
                      uuid: GPU-91a0fd64-ccc4-9ad2-ce2f-00f34d7e7a93
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H800
                      uuid: GPU-91c603e0-ea23-5526-5328-f96923e94603
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H800
                      uuid: GPU-b4b7fea5-5b72-3eec-4897-d83b0f5c496b
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H800
                      uuid: GPU-fdd50607-eb59-8d43-569f-e85596ba7e26
                host: dgx-32
                memory:
                    total: "2164194222080"
                os: Linux-5.15.0-1104-nvidia-x86_64-with-glibc2.35
                program: /home/dduab/jiayusheng/SpatialStack-omega/SpatialStack/src/qwen_vl/train/train_qwen.py
                python: CPython 3.12.13
                root: /home/dduab/jiayusheng/SpatialStack-omega/SpatialStack
                slurm:
                    cluster_name: slurm
                    conf: /cm/shared/apps/slurm/var/etc/slurm/slurm.conf
                    cpus_on_node: "224"
                    gpus: "8"
                    gpus_on_node: "8"
                    gtids: "0"
                    job_account: peilab
                    job_cpus_per_node: "224"
                    job_end_time: "1785949970"
                    job_gid: "4526"
                    job_group: dduab
                    job_id: "506723"
                    job_name: train1
                    job_nodelist: dgx-32
                    job_num_nodes: "1"
                    job_partition: normal
                    job_qos: normal_qos
                    job_start_time: "1785921170"
                    job_uid: "4526"
                    job_user: dduab
                    jobid: "506723"
                    launch_node_ipaddr: 10.22.4.12
                    localid: "0"
                    mpi_type: pmix
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: dgx-32
                    nprocs: "1"
                    ntasks: "1"
                    pmix_mapping_serv: (vector,(0,1,1))
                    pmixp_abort_agent_port: "39789"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "39899"
                    pty_win_col: "154"
                    pty_win_row: "20"
                    srun_comm_host: 10.22.4.12
                    srun_comm_port: "39509"
                    step_gpus: 0,1,2,3,4,5,6,7
                    step_id: "0"
                    step_launcher_port: "39509"
                    step_nodelist: dgx-32
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /home/dduab/jiayusheng/GD-LLM
                    submit_host: slogin-01
                    task_pid: "596785"
                    tasks_per_node: "1"
                    topology_addr: dgx-32
                    topology_addr_pattern: node
                    umask: "0007"
                    working_cluster: slurm:bcm2suheadnode-01:6817:9984:109
                startedAt: "2026-08-05T09:57:35.495012Z"
                writerId: xe0ohwxfed8wtyrhwt8sx1tizovywu7l
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
            "3":
                - 7
                - 13
                - 19
                - 66
            "4": 3.12.13
            "5": 0.25.0
            "6": 5.3.0
            "9":
                "1": transformers_trainer
            "12": 0.25.0
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
architectures:
    value:
        - Qwen3_5ForConditionalGeneration
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
batch_eval_metrics:
    value: false
bf16:
    value: true
bf16_full_eval:
    value: false
cache_dir:
    value: /project/peilab/jys/spatialstack_store/hf_cache/hub
chunk_size_feed_forward:
    value: 0
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 4
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
deepspeed:
    value: scripts/zero2_opt.json
disable_tqdm:
    value: false
do_eval:
    value: false
do_predict:
    value: false
do_train:
    value: false
dtype:
    value: bfloat16
enable_jit_checkpoint:
    value: false
eos_token_id:
    value: 248046
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: null
eval_strategy:
    value: "no"
eval_use_gather_object:
    value: false
feature_fusion_method:
    value: deepstack_language_add
fp16:
    value: false
fp16_full_eval:
    value: false
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
full_determinism:
    value: false
fusion_num_layers:
    value: 1
geometry_direct_token_mode:
    value: special17
geometry_encoder_layers:
    value:
        - 11
        - 17
        - 23
geometry_encoder_path:
    value: facebook/VGGT-Omega
geometry_encoder_type:
    value: vggt_omega_direct
geometry_fusion_layers:
    value:
        - 0
        - 1
        - 2
geometry_merger_type:
    value: mlp
geometry_token_insert_position:
    value: front
gradient_accumulation_steps:
    value: 8
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: null
group_by_modality_length:
    value: true
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
image_token_id:
    value: 248056
include_camera_token:
    value: false
include_for_metrics:
    value: []
include_num_input_tokens_seen:
    value: "no"
is_encoder_decoder:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
learning_rate:
    value: 1e-05
length_column_name:
    value: length
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: false
local_rank:
    value: -1
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: null
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
lr_scheduler_kwargs:
    value: null
lr_scheduler_type:
    value: cosine
max_grad_norm:
    value: 1
max_steps:
    value: -1
metric_for_best_model:
    value: null
mm_projector_lr:
    value: 1e-05
model/num_parameters:
    value: 5457809664
model_max_length:
    value: 12800
model_type:
    value: qwen3_5
neftune_noise_alpha:
    value: null
num_train_epochs:
    value: 1
optim:
    value: adamw_torch
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: /project/peilab/jys/qwen3_5_output/only-replace-vggt-with-omega
output_hidden_states:
    value: false
pad_token_id:
    value: 248044
parallelism_config:
    value: null
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 1
pos_encoding_type:
    value: none
prediction_loss_only:
    value: false
problem_type:
    value: null
project:
    value: huggingface
push_to_hub:
    value: false
reference_frame:
    value: first
remove_unused_columns:
    value: true
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
run_name:
    value: only-replace-vggt-with-omega
save_on_each_node:
    value: false
save_only_model:
    value: false
save_steps:
    value: 0
save_strategy:
    value: "no"
save_total_limit:
    value: 0
seed:
    value: 0
skip_memory_metrics:
    value: true
text_config:
    value:
        _name_or_path: ""
        architectures: null
        attention_bias: false
        attention_dropout: 0
        attn_output_gate: true
        bos_token_id: null
        chunk_size_feed_forward: 0
        dtype: bfloat16
        eos_token_id: 248044
        full_attention_interval: 4
        head_dim: 256
        hidden_act: silu
        hidden_size: 2560
        id2label:
            "0": LABEL_0
            "1": LABEL_1
        initializer_range: 0.02
        intermediate_size: 9216
        is_encoder_decoder: false
        label2id:
            LABEL_0: 0
            LABEL_1: 1
        layer_types:
            - linear_attention
            - linear_attention
            - linear_attention
            - full_attention
            - linear_attention
            - linear_attention
            - linear_attention
            - full_attention
            - linear_attention
            - linear_attention
            - linear_attention
            - full_attention
            - linear_attention
            - linear_attention
            - linear_attention
            - full_attention
            - linear_attention
            - linear_attention
            - linear_attention
            - full_attention
            - linear_attention
            - linear_attention
            - linear_attention
            - full_attention
            - linear_attention
            - linear_attention
            - linear_attention
            - full_attention
            - linear_attention
            - linear_attention
            - linear_attention
            - full_attention
        linear_conv_kernel_dim: 4
        linear_key_head_dim: 128
        linear_num_key_heads: 16
        linear_num_value_heads: 32
        linear_value_head_dim: 128
        mamba_ssm_dtype: float32
        max_position_embeddings: 262144
        mlp_only_layers: []
        model_type: qwen3_5_text
        mtp_num_hidden_layers: 1
        mtp_use_dedicated_embeddings: false
        num_attention_heads: 16
        num_hidden_layers: 32
        num_key_value_heads: 4
        output_attentions: false
        output_hidden_states: false
        pad_token_id: null
        partial_rotary_factor: 0.25
        problem_type: null
        return_dict: true
        rms_norm_eps: 1e-06
        rope_parameters:
            mrope_interleaved: true
            mrope_section:
                - 11
                - 11
                - 10
            partial_rotary_factor: 0.25
            rope_theta: 10000000
            rope_type: default
        tie_word_embeddings: true
        use_cache: true
        vocab_size: 248320
tf32:
    value: null
tie_word_embeddings:
    value: true
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
trackio_space_id:
    value: trackio
train_sampling_strategy:
    value: random
transformers_version:
    value: 5.3.0
use_cache:
    value: false
use_cpu:
    value: false
use_geometry_encoder:
    value: true
use_liger_kernel:
    value: false
video_token_id:
    value: 248057
vision_config:
    value:
        _name_or_path: ""
        architectures: null
        chunk_size_feed_forward: 0
        deepstack_visual_indexes: []
        depth: 24
        dtype: bfloat16
        hidden_act: gelu_pytorch_tanh
        hidden_size: 1024
        id2label:
            "0": LABEL_0
            "1": LABEL_1
        in_channels: 3
        initializer_range: 0.02
        intermediate_size: 4096
        is_encoder_decoder: false
        label2id:
            LABEL_0: 0
            LABEL_1: 1
        model_type: qwen3_5
        num_heads: 16
        num_position_embeddings: 2304
        out_hidden_size: 2560
        output_attentions: false
        output_hidden_states: false
        patch_size: 16
        problem_type: null
        return_dict: true
        spatial_merge_size: 2
        temporal_patch_size: 2
vision_end_token_id:
    value: 248054
vision_language_fusion_layers:
    value: null
vision_start_token_id:
    value: 248053
vision_tower_lr:
    value: 1e-06
warmup_ratio:
    value: null
warmup_steps:
    value: 0
weight_decay:
    value: 0.01
